src/Entity/Sample.php
<?php

namespace App\Entity;

use App\Repository\IssueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: IssueRepository::class)]
class Sample
{
    public const StateUnkown = 99;
    public const StateGood = 0;
    public const StateBad = 1;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $code = null;

    #[ORM\OneToMany(mappedBy: 'issue', targetEntity: AnalysisResult::class)]
    #[ORM\OrderBy(['id' => 'DESC'])]
    private Collection $gptResults;

    #[ORM\Column(length: 255)]
    private ?string $file = null;

    #[ORM\Column]
    private ?int $estimatedTokens = null;

    #[ORM\Column]
    private ?int $estimatedTokensUnoptimized = null;

    #[ORM\Column(nullable: true)]
    private ?int $confirmedState = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $note = null;

    #[ORM\Column(length: 255)]
    private ?string $filepath = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?int $CweId = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $codeObfuscated = null;

    public function __construct()
    {
        $this->gptResults = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    /**
     * @return Collection<int, AnalysisResult>
     */
    public function getGptResults(): Collection
    {
        return $this->gptResults;
    }

    public function getAnalyzerResultsGroupedByAnalyzer(): array
    {
        $groupedResults = [];

        foreach ($this->getGptResults() as $result) {
            $analyzer = $result->getAnalyzer();

            if (!isset($groupedResults[$result->getAnalyzer().'-'.$result->getAnalyzerVersion()])) {
                $groupedResults[$analyzer] = new ArrayCollection(); // Or another collection implementation.
            }

            $groupedResults[$analyzer]->add($result);
        }

        return $groupedResults;
    }

    public function addGptResult(AnalysisResult $gptResult): static
    {
        if (!$this->gptResults->contains($gptResult)) {
            $this->gptResults->add($gptResult);
            $gptResult->setIssue($this);
        }

        return $this;
    }

    public function removeGptResult(AnalysisResult $gptResult): static
    {
        if ($this->gptResults->removeElement($gptResult)) {
            // set the owning side to null (unless already changed)
            if ($gptResult->getIssue() === $this) {
                $gptResult->setIssue(null);
            }
        }

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): static
    {
        $this->file = $file;

        return $this;
    }

    public function getEstimatedTokens(): ?int
    {
        return $this->estimatedTokens;
    }

    public function setEstimatedTokens(int $estimatedTokens): static
    {
        $this->estimatedTokens = $estimatedTokens;

        return $this;
    }

    public function getEstimatedTokensUnoptimized(): ?int
    {
        return $this->estimatedTokensUnoptimized;
    }

    public function setEstimatedTokensUnoptimized(int $estimatedTokensUnoptimized): static
    {
        $this->estimatedTokensUnoptimized = $estimatedTokensUnoptimized;

        return $this;
    }

    public function probabilityAverage(): int
    {
        if (count($this->getGptResults()) === 0) {
            return 0;
        }

        $probabilityAverage = 0;
        foreach ($this->getGptResults() as $gptResult) {
            $probabilityAverage += $gptResult->getExploitProbability();
        }

        return $probabilityAverage;
    }

    public function getConfirmedState(): ?int
    {
        return $this->confirmedState;
    }

    public function setConfirmedState(?int $confirmedState): static
    {
        $this->confirmedState = $confirmedState;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getFilepath(): ?string
    {
        return $this->filepath;
    }

    public function setFilepath(string $filepath): static
    {
        $this->filepath = $filepath;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCweId(): ?int
    {
        return $this->CweId;
    }

    public function setCweId(?int $CweId): static
    {
        $this->CweId = $CweId;

        return $this;
    }

    public function getCodeObfuscated(): ?string
    {
        return $this->codeObfuscated;
    }

    public function setCodeObfuscated(?string $codeObfuscated): static
    {
        $this->codeObfuscated = $codeObfuscated;

        return $this;
    }

    public function getCodeContextCategory(): ?string
    {
        $contextPattern = '/- Context: (?P<category>\w+)/';
        if (preg_match($contextPattern, $this->note, $matches)) {
            $parts = explode('_', $matches['category']);
            return reset($parts);
        }

        return 'undefined';
    }
}

src/Form/IssueType.php
<?php

namespace App\Form;

use App\Entity\Sample;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IssueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('taintId')
            ->add('code')
            ->add('type')
            ->add('psalmResult')
            ->add('description')
            ->add('code');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sample::class,
        ]);
    }
}

src/Controller/IssueController.php
<?php

namespace App\Controller;

use App\Entity\AnalysisResult;
use App\Entity\Sample;
use App\Repository\GptResultRepository;
use App\Repository\IssueRepository;
use App\Service\TaintTypes;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Finder\Finder;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\Transport\Serialization\PhpSerializer;
use Symfony\Component\Process\Exception\ProcessTimedOutException;
use Symfony\Component\Process\Process;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/issue')]
class IssueController extends AbstractController
{
    #[Route('/', name: 'app_issue_index', methods: ['GET'])]
    public function index(IssueRepository $issueRepository, EntityManagerInterface $entityManager): Response
    {
        $analyzers = $entityManager->getConnection()
            ->executeQuery('SELECT DISTINCT analyzer FROM analysis_result')
            ->fetchAllAssociative();

        return $this->render('issue/index.html.twig', [
            'issues' => $issueRepository->findAll(),
            'analyzers' => $analyzers,
            'analyzer' => null,
            'type' => null,
        ]);
    }

    #[Route('/filtered', name: 'app_issue_index_filtered', methods: ['GET'])]
    public function indexFiltered(IssueRepository $issueRepository, GptResultRepository $gptResultRepository, EntityManagerInterface $entityManager, Request $request): Response
    {
        $analyzer = $request->query->get('analyzer');
        $type = $request->query->get('type');

        $analyzers = $entityManager->getConnection()
            ->executeQuery('SELECT DISTINCT analyzer FROM analysis_result')
            ->fetchAllAssociative();

        $issues = $issueRepository->findAll();
        $filtered = [];
        foreach ($issues as $issue) {
            $gptResult = $gptResultRepository->findLastFeedbackGptResultByIssue($issue, $analyzer);
            if (!$gptResult) {
                continue;
            }

            $meetsCriteria = false;

            if ($type === 'tp' && $issue->getConfirmedState() == 1 && $gptResult->getResultState() == 1) {
                $meetsCriteria = true;
            } elseif ($type === 'fp' && $issue->getConfirmedState() == 0 && $gptResult->getResultState() == 1) {
                $meetsCriteria = true;
            } elseif ($type === 'tn' && $issue->getConfirmedState() == 0 && $gptResult->getResultState() == 0) {
                $meetsCriteria = true;
            } elseif ($type === 'fn' && $issue->getConfirmedState() == 1 && $gptResult->getResultState() == 0) {
                $meetsCriteria = true;
            } elseif ($type === null) {
                $meetsCriteria = true;
            }

            if ($meetsCriteria === false) {
                continue;
            }

            $filtered[] = $issue;
        }

        return $this->render('issue/index.html.twig', [
            'issues' => $filtered,
            'analyzers' => $analyzers,
            'analyzer' => $analyzer,
            'type' => $type,
        ]);
    }

    #[Route('/{id}', name: 'app_issue_show', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function show(Sample $issue, ManagerRegistry $managerRegistry, GptResultRepository $gptResultRepository): Response
    {
        $phpSerializer = new PhpSerializer();
        $connection = $managerRegistry->getConnection();
        $result = $connection
            ->prepare('SELECT * FROM messenger_messages ORDER BY created_at')
            ->executeQuery()
            ->fetchAllAssociative();

        $position = 0;
        $result = array_filter(
            array_map(function ($item) use ($phpSerializer, $issue, &$position) {
                $item['message'] = $phpSerializer->decode($item)->getMessage();
                $item['position'] = $position;
                $position++;
                if ($item['message']->getId() === $issue->getId()) {
                    return $item;
                }
            }, $result));

        $resultsByAnalyzer = [];
        foreach ($issue->getAnalyzerResultsGroupedByAnalyzer() as $analyzer => $groupedResult) {
            $resultsByAnalyzer[$analyzer][] = $gptResultRepository->findLastFeedbackGptResultByIssue($issue, $analyzer);
        }

        return $this->render('issue/show.html.twig', [
            'queue' => $result,
            'issue' => $issue,
            'resultsByAnalyzer' => $resultsByAnalyzer,
        ]);
    }

    #[Route('/{id}/init-sandbox/{gptResult}', name: 'app_issue_init_sandbox', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function initSandbox(Sample $issue, AnalysisResult $gptResult, string $projectDir): Response
    {
        // get source directory of sample
        $sourceDirectory = $projectDir.dirname(dirname($issue->getFilepath()));

        // find sample files (named index.php or sample.php first, than any php file (legacy format with CWE_* names)
        $finder = new Finder();
        $sourceFiles = $finder->in($sourceDirectory)->files()->name(['sample.php', 'index.php', 'CWE_*.php'])->getIterator();
        $sourceFiles->rewind();
        $sourceFile = $sourceFiles->current()->getRealPath();
        $targetFile = "{$projectDir}/sandbox/public/index.php";

        $filesystem = new Filesystem();
        $filesystem->copy($sourceFile, $targetFile, true);

        // remove comments
        $targetFileContent = preg_replace('#<!--(.*?)-->#ism', '', file_get_contents($targetFile));
        file_put_contents($targetFile, $targetFileContent);

        // setup mysql database
        $sqlFile = "{$sourceDirectory}/init.sql";
        if (is_file($sqlFile)) {
            $dockerfile = file_get_contents("{$sourceDirectory}/Dockerfile");
            if (strpos($dockerfile, 'sqlite3') !== false) {
                if (is_file("{$projectDir}/db/database.db")) {
                    unlink("{$projectDir}/db/database.db");
                }
                echo "sqlite3 -init $sqlFile {$projectDir}/db/database.db '.exit'";
                system("sqlite3 -init '{$sqlFile}' '{projectDir}/db/database.db' '.exit'");
            } else {
                system("mysql -hmysql -uroot -e 'DROP DATABASE IF EXISTS myDB;'");
                system("mysql -hmysql -uroot < '{$sqlFile}'");
            }
        }

        $process = Process::fromShellCommandline($gptResult->getExploitExample());
        $process->setTimeout(59);
        try {
            $process->run();
        } catch (ProcessTimedOutException $e) {
            return false;
        } finally {
            return $this->render('issue/result.html.twig', [
                'issue' => $issue,
                'proccess' => $process,
            ]);
        }
    }

    public function getPsalmResultsArray($projectDir, $folderName): array
    {
        $psalmResultFile = $projectDir.DIRECTORY_SEPARATOR.'data/wordpress/results'.DIRECTORY_SEPARATOR.$folderName.'.txt';
        $text = file_get_contents($psalmResultFile);

        // Remove the psalm footer section
        $footerPattern = '/\n-{12,}\n.*?$/s';
        $text = preg_replace($footerPattern, '', $text);

        $pattern = '/ERROR: ([\w\s]+) - (\S+):(\d+:\d+) - (.+?)\n([\s\S]+?)(?=\n\nERROR|$)/';
        preg_match_all($pattern, $text, $matches, PREG_SET_ORDER);

        $errors = [];
        foreach ($matches as $match) {
            $errors[] = [
                'errorType' => $match[1],
                'errorId' => TaintTypes::getIdByName($match[1]),
                'file' => $match[2].':'.$match[3],
                'description' => $match[4],
                'content' => $match[5],
            ];
        }

        return $errors;
    }
}

templates/issue/index.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 flex justify-between align-middle">
        <h1 class="text-xl align-middle font-semibold leading-6 text-gray-900">Samples overview</h1>
        <form method="get" action="{{ path('app_issue_index_filtered') }}">
            <div class="flex space-x-2">
                <select name="analyzer" class="text-sm block w-1/2 bg-white border border-gray-300 text-gray-700 py-1 px-1.5 rounded leading-tight focus:outline-none focus:border-blue-500">
                    <option value="" disabled selected>Select Analyzer</option>
                    {% for analyzerOption in analyzers %}
                        <option value="{{ analyzerOption.analyzer }}" {% if analyzerOption.analyzer == analyzer %}selected{% endif %}>{{ analyzerOption.analyzer }}</option>
                    {% endfor %}
                </select>
                <select name="type" class="text-sm block w-1/2 bg-white border border-gray-300 text-gray-700 py-1 px-1.5 rounded leading-tight focus:outline-none focus:border-blue-500">
                    <option value="" disabled selected>Select Type</option>
                    <option value="tp" {% if type == 'tp' %}selected{% endif %}>True Positive</option>
                    <option value="fp" {% if type == 'fp' %}selected{% endif %}>False Positive</option>
                    <option value="tn" {% if type == 'tn' %}selected{% endif %}>True Negative</option>
                    <option value="fn" {% if type == 'fn' %}selected{% endif %}>False Negative</option>
                </select>
                <button type="submit" class="block w-32 rounded-md bg-gray-500 px-1.5 py-1 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Filter</button>
            </div>
        </form>
    </div>
{% endblock %}

{% block body %}
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <p class="mt-6 text-sm text-gray-700">List of all samples</p>
        </div>
    </div>
    <div class="mt-8 flow-root">
        <div class="-mx-4 -my-2 sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle">
                <table class="min-w-full border-separate border-spacing-0">
                    <thead>
                    <tr>
                        <th scope="col"
                            class="sticky w-2/12 top-0 z-10 border-b border-gray-300 bg-white bg-opacity-75 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter sm:pl-6 lg:pl-8">
                            Sample
                        </th>
                        <th scope="col"
                            class="sticky w-2/12 top-0 z-10 border-b border-gray-300 bg-white bg-opacity-75 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter sm:pl-6 lg:pl-8">
                           CWE
                        </th>
                        <th scope="col"
                            class="sticky w-2/12 top-0 z-10 border-b border-gray-300 bg-white bg-opacity-75 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter sm:pl-6 lg:pl-8">
                            Category
                        </th>
                        <th scope="col"
                            class="sticky w-2/12 top-0 z-10 border-b border-gray-300 bg-white bg-opacity-75 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter sm:pl-6 lg:pl-8">
                            Confirmed-State
                        </th>
                        <th scope="col"
                            class="sticky w-8/12 top-0 z-10 border-b border-gray-300 bg-white bg-opacity-75 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter sm:pl-6 lg:pl-8">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for issue in issues %}
                        <tr>
                            <td class="whitespace-nowrap border-b border-gray-200 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 lg:pl-8">{{ issue.name }}</td>
                            <td class="whitespace-nowrap border-b border-gray-200 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 lg:pl-8">{{ issue.cweid }}</td>
                            <td class="whitespace-nowrap border-b border-gray-200 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 lg:pl-8">{{ issue.codeContextCategory }}</td>
                            <td class="whitespace-nowrap border-b border-gray-200 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 lg:pl-8">{{ issue.confirmedState }}</td>
                            <td class="flex justify-end relative whitespace-nowrap border-b border-gray-200 py-4 pr-4 pl-3 text-right text-sm font-medium sm:pr-8 lg:pr-8">
                                <a href="{{ path('app_issue_show', {'id': issue.id}) }}"
                                   class="block w-32 rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                                    Details
                                </a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="4">No records found.</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/issue/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Issue{% endblock %}

{% block body %}
    <h1>Create new Issue</h1>

    {{ include('issue/_form.html.twig') }}

    <a href="{{ path('app_issue_index') }}">back to list</a>
{% endblock %}

templates/issue/result.html.twig
{% extends 'base.html.twig' %}

{% block title %}Issue{% endblock %}

{% block header %}

    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <h1 class="text-xl font-semibold leading-6 text-gray-900">Sample {{issue.name}}</h1>
    </div>

{% endblock %}

{% block body %}
    <div class="[white-space: pre-wrap] bg-black text-white font-mono p-4 shadow-lg border border-gray-700">
        <textarea class="[white-space:pre-wrap] p-0 resize-none font-mono leading-normal w-full h-64 bg-black text-white border-none outline-none" disabled>
$ {{proccess.commandline|raw }}
{{proccess.output|raw }}
        </textarea>
    </div>
{% endblock %}